# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  ".github/pull_request_template.md",
  "renovate.json",
  "CHANGELOG.md",
  "docs/DEVELOPMENT.md",
  "jreleaser.yml",
  ".mvn/settings.xml",
  "**/*/pmd_default_java.xml",
  "README.md",
  ".gitleaks-test/tests/suite-report-approved.jsonl",
  "SECURITY.md",
  "DEVELOPMENT.md",
  "CONTRIBUTING.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 diggsweden/wallet-requirements"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["CODE_OF_CONDUCT.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributor Covenant"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["GOVERNANCE.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 diggsweden/wallet-requirements"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]

path = [
    "**/*/eclipse-java-google-style.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "google/styleguide"
SPDX-License-Identifier = "CC-BY-3.0"


[[annotations]]
path = [
    "**/*/google_checks.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "checkstyle/checkstyle"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "mvnw",
    "mvnw.cmd",
    ".mvn/wrapper/maven-wrapper.jar",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Apache Software Foundation (ASF)"
SPDX-License-Identifier = "Apache-2.0"